Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Group2Intex.Models;

namespace Group2Intex.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        
        public CartSummaryViewComponent(Cart cartService)
        {
            this.cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/ProjectTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Group2Intex.Models;

namespace Group2Intex.Components
{
    public class ProjectTypesViewComponent :ViewComponent
    {
        private IIntexRepository _waterRepo;

        //Constructor
        public ProjectTypesViewComponent(IIntexRepository temp) 
        {
            _waterRepo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedProjectType = RouteData?.Values["projectType"];

            var projectTypes = _waterRepo.Projects
                .Select(x => x.ProjectType)
                .Distinct()
                .OrderBy(x => x);

            return View(projectTypes);
        }
    }
}

Views/Shared/ProjectSummary.cshtml
@using Group2Intex.Infrastructure
@{
    ViewData["Title"] = "ProjectSummary";
}

@model Project

<div class="card m-1 p-1">
    <h4>
        @Model.ProjectName
        <span class="badge rounded-pill bg-primary text-white float-end"><small>@Model.ProjectImpact served</small></span>
    </h4>

    <ul>
        <li>Project Type: @Model.ProjectType</li>
        <li>Regional Program: @Model.ProgramName</li>
        <li>Installation: @Model.ProjectInstallation</li>
        <li>Phase: @Model.ProjectPhase</li>
    </ul>

    <form id=@Model.ProjectId method="post" asp-page="/Cart">
        <input type="hidden" asp-for="ProjectId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <button type="submit" class="btn-outline-success btn-sm float-end">Donate</button>
    </form>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group2Intex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group2Intex.styles.css" asp-append-version="true" />
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Group2Intex</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <div class="col-6 navbar-text text-end">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:project-types />
        </div>
        <div class="container col-9">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Group2Intex - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>